[font]
# The normal (roman) font face to use.
normal.family = "Iosevka Nerd Font"
normal.style = "Regular"

# The bold font face
bold.family = "Iosevka Nerd Font"
bold.style = "Bold"

# The italic font face
italic.family = "Iosevka Nerd Font"
italic.style = "Italic"

# The bold italic font face
bold_italic.family = "Iosevka Nerd Font"
bold_italic.style = "Bold Italic"

# Optionally, adjust the size:
size = 14.0